meta_product_name: "OneCrowd"
meta_title: "OneCrowd | Elite investments for all"
meta_description: "Co-invest in exclusive assets"
meta_image: "logo.png"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
